### ISSUE TITLE
So does Valorant work or not?

### ISSUE THREAD

**Issue by SouperNinja** [ryanrudolfoba/SecureBootForSteamDeck#1]
I was thinking about going full windows 11 since I've been using windows 10 on steamdeck for valorant but when you say "vanguard still complains about secure boot" does it still not let you into valorant or does it just give a warning or something?

**Comment by ryanrudolfoba** [comment]
Valorant works if on Windows 10.

But if you go Windows 11 it doesnt.

**Comment by ryanrudolfoba** [comment]
Closing this issue. Valve needs to release the needed keys to activate and enable Secure Boot.

Using self signed keys will trigger and activate Secure Boot, but it is not a guarantee that games will work - example Valorant.
