### ISSUE TITLE
Is there a way to disable secureboot without keys?

### ISSUE THREAD

**Issue by Synaps33** [ryanrudolfoba/SecureBootForSteamDeck#2]
I was trying to create secureboot on a deck from an live fedora distro, and now my keys are gone. Is there a way to revert uefi secureboot settings?

**Comment by ryanrudolfoba** [comment]
using a live distro is not recommended because when you reboot the keys that have been generated will be gone. 

Once you enable secureboot by generating your own keys, it is impossible to disable and revert back if the generated keys are missing.

**Comment by ryanrudolfoba** [comment]
Without the keys you cant disable secure boot.


![](https://user-images.githubusercontent.com/98122529/237976202-acc4965d-06f2-4d24-996e-07ed4d3e8f29.png)
